<?php

namespace ContainerV2qyd9n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XqqGVuMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XqqGVuM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XqqGVuM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CartController::delete' => ['privates', '.service_locator.O6jAZXE', 'get_ServiceLocator_O6jAZXEService', true],
            'App\\Controller\\CartController::edit' => ['privates', '.service_locator.O6jAZXE', 'get_ServiceLocator_O6jAZXEService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.drC7Dr_', 'get_ServiceLocator_DrC7DrService', true],
            'App\\Controller\\CartController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CartController::show' => ['privates', '.service_locator.hrv7FUZ', 'get_ServiceLocator_Hrv7FUZService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.oZvIfEr', 'get_ServiceLocator_OZvIfErService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.oZvIfEr', 'get_ServiceLocator_OZvIfErService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CartController:delete' => ['privates', '.service_locator.O6jAZXE', 'get_ServiceLocator_O6jAZXEService', true],
            'App\\Controller\\CartController:edit' => ['privates', '.service_locator.O6jAZXE', 'get_ServiceLocator_O6jAZXEService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.drC7Dr_', 'get_ServiceLocator_DrC7DrService', true],
            'App\\Controller\\CartController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CartController:show' => ['privates', '.service_locator.hrv7FUZ', 'get_ServiceLocator_Hrv7FUZService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.oZvIfEr', 'get_ServiceLocator_OZvIfErService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.oZvIfEr', 'get_ServiceLocator_OZvIfErService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CartController::delete' => '?',
            'App\\Controller\\CartController::edit' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::new' => '?',
            'App\\Controller\\CartController::show' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CartController:delete' => '?',
            'App\\Controller\\CartController:edit' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:new' => '?',
            'App\\Controller\\CartController:show' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
