<?php

namespace ContainerV2qyd9n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O6jAZXE.App\Entity\Cart' shared service.
     *
     * @return \App\Entity\Cart
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O6jAZXE": it needs an instance of "App\\Entity\\Cart" but this type has been excluded in "config/services.yaml".');
    }
}
