<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV2qyd9n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV2qyd9n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV2qyd9n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV2qyd9n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV2qyd9n\App_KernelDevDebugContainer([
    'container.build_hash' => 'V2qyd9n',
    'container.build_id' => '0ee5cf61',
    'container.build_time' => 1713088925,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV2qyd9n');
