<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1VPn74\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1VPn74/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX1VPn74.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX1VPn74\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX1VPn74\App_KernelDevDebugContainer([
    'container.build_hash' => 'X1VPn74',
    'container.build_id' => 'f60b0409',
    'container.build_time' => 1713288928,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1VPn74');
